[package]
name = "file-store"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tempfile = "3.27.0"
thiserror = "2.0.20"
tracing = "0.1.44"
uuid = { version = "1.24.0", features = ["serde", "v4"] }
