[package]
name = "routes"
version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actix-web = { version = "4.14.1", default-features = false, features = [
    "macros",
    "compress-brotli",
    "compress-gzip",
    "cookies",
    "rustls-0_23",
] }
utoipa = { version = "5.5.0", features = [
    "actix_extras",
    "macros",
    "non_strict_integers",
    "preserve_order",
    "uuid",
    "time",
    "openapi_extensions",
] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
time = { version = "0.3.55", features = ["serde-well-known", "formatting", "parsing", "macros"] }
uuid = { version = "1.24.0", features = ["serde", "v4", "v7"] }
routes-macros = { path = "../routes-macros" }
