[package]
name = "http-client"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
ureq = { version = "3.4.0", default-features = false, features = ["json", "gzip", "rustls"] }
reqwest = { version = "0.12.28", features = [
    "stream",
    "multipart",
    "rustls-tls-native-roots",
    "rustls-tls",
    "json",
], default-features = false }
hyper-util = { version = "0.1.20", features = [
    "client",
    "client-legacy",
    "tokio",
] }
tower-service = "0.3.3"
cidr = "0.3.2"
url = "2.5.8"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["full"] }
