name: Run the indexing fuzzer

on:
  push:
    branches:
      - main

jobs:
  fuzz:
    name: Setup the action
    runs-on: ubuntu-latest
    timeout-minutes: 4320 # 72h
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@38ae5351029910ad7674ccfad89c37cbd636f3c4 # 1.91.1
        with:
          toolchain: 1.91.1

      # Run benchmarks
      - name: Run the fuzzer
        run: |
          cargo run --release --bin fuzz-indexing
